/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-Object-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_AdditionalSupportOptions_H_
#define	_AdditionalSupportOptions_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdditionalSupportOptions {
	AdditionalSupportOptions_vMDStop	= 0,
	AdditionalSupportOptions_vMDReset	= 1,
	AdditionalSupportOptions_select	= 2,
	AdditionalSupportOptions_alterProgramInvocationAttributes	= 3,
	AdditionalSupportOptions_initiateUnitControlLoad	= 4,
	AdditionalSupportOptions_unitControlLoadSegment	= 5,
	AdditionalSupportOptions_unitControlUpload	= 6,
	AdditionalSupportOptions_startUnitControl	= 7,
	AdditionalSupportOptions_stopUnitControl	= 8,
	AdditionalSupportOptions_createUnitControl	= 9,
	AdditionalSupportOptions_addToUnitControl	= 10,
	AdditionalSupportOptions_removeFromUnitControl	= 11,
	AdditionalSupportOptions_getUnitControlAttributes	= 12,
	AdditionalSupportOptions_loadUnitControlFromFile	= 13,
	AdditionalSupportOptions_storeUnitControlToFile	= 14,
	AdditionalSupportOptions_deleteUnitControl	= 15,
	AdditionalSupportOptions_defineEventConditionList	= 16,
	AdditionalSupportOptions_deleteEventConditionList	= 17,
	AdditionalSupportOptions_addEventConditionListReference	= 18,
	AdditionalSupportOptions_removeEventConditionListReference	= 19,
	AdditionalSupportOptions_getEventConditionListAttributes	= 20,
	AdditionalSupportOptions_reportEventConditionListStatus	= 21,
	AdditionalSupportOptions_alterEventConditionListMonitoring	= 22
} e_AdditionalSupportOptions;

/* AdditionalSupportOptions */
typedef BIT_STRING_t	 AdditionalSupportOptions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalSupportOptions;
asn_struct_free_f AdditionalSupportOptions_free;
asn_struct_print_f AdditionalSupportOptions_print;
asn_constr_check_f AdditionalSupportOptions_constraint;
ber_type_decoder_f AdditionalSupportOptions_decode_ber;
der_type_encoder_f AdditionalSupportOptions_encode_der;
xer_type_decoder_f AdditionalSupportOptions_decode_xer;
xer_type_encoder_f AdditionalSupportOptions_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalSupportOptions_H_ */
