/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_AlarmEnrollmentSummary_H_
#define	_AlarmEnrollmentSummary_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectName.h"
#include "Unsigned8.h"
#include "EC-State.h"
#include "BOOLEAN.h"
#include "AlarmAckRule.h"
#include "EE-State.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ApplicationReference;
struct EN_Additional_Detail;
struct EventTime;

/* AlarmEnrollmentSummary */
typedef struct AlarmEnrollmentSummary {
	ObjectName_t	 eventEnrollmentName;
	struct ApplicationReference	*clientApplication	/* OPTIONAL */;
	Unsigned8_t	 severity;
	EC_State_t	 currentState;
	struct EN_Additional_Detail	*displayEnhancement	/* OPTIONAL */;
	BOOLEAN_t	*notificationLost	/* DEFAULT FALSE */;
	AlarmAckRule_t	 alarmAcknowledgmentRule;
	EE_State_t	*enrollmentState	/* OPTIONAL */;
	struct EventTime	*timeOfLastTransitionToActive	/* OPTIONAL */;
	struct EventTime	*timeActiveAcknowledged	/* OPTIONAL */;
	struct EventTime	*timeOfLastTransitionToIdle	/* OPTIONAL */;
	struct EventTime	*timeIdleAcknowledged	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlarmEnrollmentSummary_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlarmEnrollmentSummary;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ApplicationReference.h"
#include "EN-Additional-Detail.h"
#include "EventTime.h"

#endif	/* _AlarmEnrollmentSummary_H_ */
