/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-Object-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_AlarmAckRule_H_
#define	_AlarmAckRule_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlarmAckRule {
	AlarmAckRule_none	= 0,
	AlarmAckRule_simple	= 1,
	AlarmAckRule_ack_active	= 2,
	AlarmAckRule_ack_all	= 3
} e_AlarmAckRule;

/* AlarmAckRule */
typedef long	 AlarmAckRule_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlarmAckRule;
asn_struct_free_f AlarmAckRule_free;
asn_struct_print_f AlarmAckRule_print;
asn_constr_check_f AlarmAckRule_constraint;
ber_type_decoder_f AlarmAckRule_decode_ber;
der_type_encoder_f AlarmAckRule_encode_der;
xer_type_decoder_f AlarmAckRule_decode_xer;
xer_type_encoder_f AlarmAckRule_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AlarmAckRule_H_ */
