/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-Environment-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_ApplicationReference_H_
#define	_ApplicationReference_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AP-title.h"
#include "AP-invocation-identifier.h"
#include "AE-qualifier.h"
#include "AE-invocation-identifier.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ApplicationReference */
typedef struct ApplicationReference {
	AP_title_t	*ap_title	/* OPTIONAL */;
	AP_invocation_identifier_t	*ap_invocation_id	/* OPTIONAL */;
	AE_qualifier_t	*ae_qualifier	/* OPTIONAL */;
	AE_invocation_identifier_t	*ae_invocation_id	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ApplicationReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ApplicationReference;

#ifdef __cplusplus
}
#endif

#endif	/* _ApplicationReference_H_ */
