/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Authentication_value_H_
#define	_Authentication_value_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Authentication-value */
typedef NULL_t	 Authentication_value_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Authentication_value;
asn_struct_free_f Authentication_value_free;
asn_struct_print_f Authentication_value_print;
asn_constr_check_f Authentication_value_constraint;
ber_type_decoder_f Authentication_value_decode_ber;
der_type_encoder_f Authentication_value_encode_der;
xer_type_decoder_f Authentication_value_decode_xer;
xer_type_encoder_f Authentication_value_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Authentication_value_H_ */
