/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Conclude_RequestPDU_H_
#define	_Conclude_RequestPDU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Conclude-RequestPDU */
typedef NULL_t	 Conclude_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Conclude_RequestPDU;
asn_struct_free_f Conclude_RequestPDU_free;
asn_struct_print_f Conclude_RequestPDU_print;
asn_constr_check_f Conclude_RequestPDU_constraint;
ber_type_decoder_f Conclude_RequestPDU_decode_ber;
der_type_encoder_f Conclude_RequestPDU_encode_der;
xer_type_decoder_f Conclude_RequestPDU_decode_xer;
xer_type_encoder_f Conclude_RequestPDU_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Conclude_RequestPDU_H_ */
