/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Confirmed_ErrorPDU_H_
#define	_Confirmed_ErrorPDU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Unsigned32.h"
#include "ServiceError.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Confirmed-ErrorPDU */
typedef struct Confirmed_ErrorPDU {
	Unsigned32_t	 invokeID;
	Unsigned32_t	*modifierPosition	/* OPTIONAL */;
	ServiceError_t	 serviceError;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Confirmed_ErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Confirmed_ErrorPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _Confirmed_ErrorPDU_H_ */
