/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "Confirmed-ErrorPDU.h"

static asn_TYPE_member_t asn_MBR_Confirmed_ErrorPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Confirmed_ErrorPDU, invokeID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"invokeID"
		},
	{ ATF_POINTER, 1, offsetof(struct Confirmed_ErrorPDU, modifierPosition),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modifierPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Confirmed_ErrorPDU, serviceError),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceError"
		},
};
static ber_tlv_tag_t asn_DEF_Confirmed_ErrorPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Confirmed_ErrorPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* invokeID at 1200 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* modifierPosition at 1201 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* serviceError at 1202 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Confirmed_ErrorPDU_specs_1 = {
	sizeof(struct Confirmed_ErrorPDU),
	offsetof(struct Confirmed_ErrorPDU, _asn_ctx),
	asn_MAP_Confirmed_ErrorPDU_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Confirmed_ErrorPDU = {
	"Confirmed-ErrorPDU",
	"Confirmed-ErrorPDU",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Confirmed_ErrorPDU_tags_1,
	sizeof(asn_DEF_Confirmed_ErrorPDU_tags_1)
		/sizeof(asn_DEF_Confirmed_ErrorPDU_tags_1[0]), /* 1 */
	asn_DEF_Confirmed_ErrorPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_Confirmed_ErrorPDU_tags_1)
		/sizeof(asn_DEF_Confirmed_ErrorPDU_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Confirmed_ErrorPDU_1,
	3,	/* Elements count */
	&asn_SPC_Confirmed_ErrorPDU_specs_1	/* Additional specs */
};

