/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_CS_GetProgramInvocationAttributes_Response_H_
#define	_CS_GetProgramInvocationAttributes_Response_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "NULL.h"
#include "VisibleString.h"
#include "Identifier.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CS_GetProgramInvocationAttributes_Response__control_PR {
	CS_GetProgramInvocationAttributes_Response__control_PR_NOTHING,	/* No components present */
	CS_GetProgramInvocationAttributes_Response__control_PR_controlling,
	CS_GetProgramInvocationAttributes_Response__control_PR_controlled,
	CS_GetProgramInvocationAttributes_Response__control_PR_normal
} CS_GetProgramInvocationAttributes_Response__control_PR;
typedef enum CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_PR {
	CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_PR_NOTHING,	/* No components present */
	CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_PR_freeRunning,
	CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_PR_cycleLimited,
	CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_PR_stepLimited
} CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_PR;
typedef enum CS_GetProgramInvocationAttributes_Response__control__controlled_PR {
	CS_GetProgramInvocationAttributes_Response__control__controlled_PR_NOTHING,	/* No components present */
	CS_GetProgramInvocationAttributes_Response__control__controlled_PR_controllingPI,
	CS_GetProgramInvocationAttributes_Response__control__controlled_PR_none
} CS_GetProgramInvocationAttributes_Response__control__controlled_PR;

/* CS-GetProgramInvocationAttributes-Response */
typedef struct CS_GetProgramInvocationAttributes_Response {
	long	 errorCode;
	struct CS_GetProgramInvocationAttributes_Response__control {
		CS_GetProgramInvocationAttributes_Response__control_PR present;
		union CS_GetProgramInvocationAttributes_Response__control_u {
			struct CS_GetProgramInvocationAttributes_Response__control__controlling {
				struct CS_GetProgramInvocationAttributes_Response__control__controlling__controlledPI {
					A_SEQUENCE_OF(Identifier_t) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} controlledPI;
				VisibleString_t	*programLocation	/* OPTIONAL */;
				struct CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode {
					CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_PR present;
					union CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_u {
						NULL_t	 freeRunning;
						long	 cycleLimited;
						long	 stepLimited;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} runningMode;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} controlling;
			struct CS_GetProgramInvocationAttributes_Response__control__controlled {
				CS_GetProgramInvocationAttributes_Response__control__controlled_PR present;
				union CS_GetProgramInvocationAttributes_Response__control__controlled_u {
					Identifier_t	 controllingPI;
					NULL_t	 none;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} controlled;
			NULL_t	 normal;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} control;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CS_GetProgramInvocationAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CS_GetProgramInvocationAttributes_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _CS_GetProgramInvocationAttributes_Response_H_ */
