/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "CS-Start-Request.h"

static asn_TYPE_member_t asn_MBR_controlling_3[] = {
	{ ATF_POINTER, 2, offsetof(struct CS_Start_Request__controlling, startLocation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"startLocation"
		},
	{ ATF_POINTER, 1, offsetof(struct CS_Start_Request__controlling, startCount),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_StartCount,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"startCount"
		},
};
static ber_tlv_tag_t asn_DEF_controlling_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_controlling_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* startLocation at 1762 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* startCount at 1763 */
};
static asn_SEQUENCE_specifics_t asn_SPC_controlling_specs_3 = {
	sizeof(struct CS_Start_Request__controlling),
	offsetof(struct CS_Start_Request__controlling, _asn_ctx),
	asn_MAP_controlling_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_controlling_3 = {
	"controlling",
	"controlling",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_controlling_tags_3,
	sizeof(asn_DEF_controlling_tags_3)
		/sizeof(asn_DEF_controlling_tags_3[0]), /* 1 */
	asn_DEF_controlling_tags_3,	/* Same as above */
	sizeof(asn_DEF_controlling_tags_3)
		/sizeof(asn_DEF_controlling_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_controlling_3,
	2,	/* Elements count */
	&asn_SPC_controlling_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CS_Start_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_Start_Request, choice.normal),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"normal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_Start_Request, choice.controlling),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_controlling_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"controlling"
		},
};
static ber_tlv_tag_t asn_DEF_CS_Start_Request_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CS_Start_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 0 }, /* normal at 1760 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* controlling at 1762 */
};
static asn_CHOICE_specifics_t asn_SPC_CS_Start_Request_specs_1 = {
	sizeof(struct CS_Start_Request),
	offsetof(struct CS_Start_Request, _asn_ctx),
	offsetof(struct CS_Start_Request, present),
	sizeof(((struct CS_Start_Request *)0)->present),
	asn_MAP_CS_Start_Request_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CS_Start_Request = {
	"CS-Start-Request",
	"CS-Start-Request",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	asn_DEF_CS_Start_Request_tags_1,
	sizeof(asn_DEF_CS_Start_Request_tags_1)
		/sizeof(asn_DEF_CS_Start_Request_tags_1[0]), /* 1 */
	asn_DEF_CS_Start_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_CS_Start_Request_tags_1)
		/sizeof(asn_DEF_CS_Start_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CS_Start_Request_1,
	2,	/* Elements count */
	&asn_SPC_CS_Start_Request_specs_1	/* Additional specs */
};

