/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "DataParameters.h"

static asn_TYPE_member_t asn_MBR_floating_point_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DataParameters__floating_point, total),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"total"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataParameters__floating_point, exponent),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"exponent"
		},
};
static ber_tlv_tag_t asn_DEF_floating_point_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_floating_point_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 }, /* total at 3318 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 } /* exponent at 3319 */
};
static asn_SEQUENCE_specifics_t asn_SPC_floating_point_specs_5 = {
	sizeof(struct DataParameters__floating_point),
	offsetof(struct DataParameters__floating_point, _asn_ctx),
	asn_MAP_floating_point_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_floating_point_5 = {
	"floating-point",
	"floating-point",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_floating_point_tags_5,
	sizeof(asn_DEF_floating_point_tags_5)
		/sizeof(asn_DEF_floating_point_tags_5[0]) - 1, /* 1 */
	asn_DEF_floating_point_tags_5,	/* Same as above */
	sizeof(asn_DEF_floating_point_tags_5)
		/sizeof(asn_DEF_floating_point_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_floating_point_5,
	2,	/* Elements count */
	&asn_SPC_floating_point_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DataParameters_1[] = {
	{ ATF_POINTER, 9, offsetof(struct DataParameters, bit_string),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bit-string"
		},
	{ ATF_POINTER, 8, offsetof(struct DataParameters, integer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"integer"
		},
	{ ATF_POINTER, 7, offsetof(struct DataParameters, Unsigned),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unsigned"
		},
	{ ATF_POINTER, 6, offsetof(struct DataParameters, floating_point),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_floating_point_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"floating-point"
		},
	{ ATF_POINTER, 5, offsetof(struct DataParameters, octet_string),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octet-string"
		},
	{ ATF_POINTER, 4, offsetof(struct DataParameters, visible_string),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"visible-string"
		},
	{ ATF_POINTER, 3, offsetof(struct DataParameters, binary_time),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"binary-time"
		},
	{ ATF_POINTER, 2, offsetof(struct DataParameters, bcd),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bcd"
		},
	{ ATF_POINTER, 1, offsetof(struct DataParameters, mmsString),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mmsString"
		},
};
static ber_tlv_tag_t asn_DEF_DataParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DataParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* bit-string at 3314 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* integer at 3315 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* unsigned at 3316 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* floating-point at 3318 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 4, 0, 0 }, /* octet-string at 3320 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 5, 0, 0 }, /* visible-string at 3321 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 6, 0, 0 }, /* binary-time at 3322 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 7, 0, 0 }, /* bcd at 3323 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 8, 0, 0 } /* mmsString at 3324 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DataParameters_specs_1 = {
	sizeof(struct DataParameters),
	offsetof(struct DataParameters, _asn_ctx),
	asn_MAP_DataParameters_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DataParameters = {
	"DataParameters",
	"DataParameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DataParameters_tags_1,
	sizeof(asn_DEF_DataParameters_tags_1)
		/sizeof(asn_DEF_DataParameters_tags_1[0]), /* 1 */
	asn_DEF_DataParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_DataParameters_tags_1)
		/sizeof(asn_DEF_DataParameters_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DataParameters_1,
	9,	/* Elements count */
	&asn_SPC_DataParameters_specs_1	/* Additional specs */
};

