/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_DefineEventAction_Request_H_
#define	_DefineEventAction_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectName.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConfirmedServiceRequest;
struct Request_Detail;
struct Modifier;

/* DefineEventAction-Request */
typedef struct DefineEventAction_Request {
	ObjectName_t	 eventActionName;
	struct DefineEventAction_Request__listOfModifier {
		A_SEQUENCE_OF(struct Modifier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfModifier;
	struct ConfirmedServiceRequest	*confirmedServiceRequest;
	struct Request_Detail	*cs_extension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineEventAction_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineEventAction_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConfirmedServiceRequest.h"
#include "Request-Detail.h"
#include "Modifier.h"

#endif	/* _DefineEventAction_Request_H_ */
