/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "DefineEventCondition-Request.h"

static int asn_DFL_4_set_64(int set_value, void **sptr) {
	Priority_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 64 */
		*st = 64;
		return 0;
	} else {
		/* Test default value 64 */
		return (*st == 64);
	}
}
static int asn_DFL_5_set_64(int set_value, void **sptr) {
	Unsigned8_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 64 */
		*st = 64;
		return 0;
	} else {
		/* Test default value 64 */
		return (*st == 64);
	}
}
static asn_TYPE_member_t asn_MBR_DefineEventCondition_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DefineEventCondition_Request, eventConditionName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventConditionName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DefineEventCondition_Request, Class),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EC_Class,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"class"
		},
	{ ATF_POINTER, 5, offsetof(struct DefineEventCondition_Request, priority),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Priority,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_4_set_64,	/* DEFAULT 64 */
		"priority"
		},
	{ ATF_POINTER, 4, offsetof(struct DefineEventCondition_Request, severity),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_5_set_64,	/* DEFAULT 64 */
		"severity"
		},
	{ ATF_POINTER, 3, offsetof(struct DefineEventCondition_Request, alarmSummaryReports),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alarmSummaryReports"
		},
	{ ATF_POINTER, 2, offsetof(struct DefineEventCondition_Request, monitoredVariable),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_VariableSpecification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"monitoredVariable"
		},
	{ ATF_POINTER, 1, offsetof(struct DefineEventCondition_Request, evaluationInterval),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"evaluationInterval"
		},
};
static ber_tlv_tag_t asn_DEF_DefineEventCondition_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DefineEventCondition_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventConditionName at 2409 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* class at 2410 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* priority at 2411 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* severity at 2412 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* alarmSummaryReports at 2413 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* monitoredVariable at 2414 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 } /* evaluationInterval at 2415 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DefineEventCondition_Request_specs_1 = {
	sizeof(struct DefineEventCondition_Request),
	offsetof(struct DefineEventCondition_Request, _asn_ctx),
	asn_MAP_DefineEventCondition_Request_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DefineEventCondition_Request = {
	"DefineEventCondition-Request",
	"DefineEventCondition-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DefineEventCondition_Request_tags_1,
	sizeof(asn_DEF_DefineEventCondition_Request_tags_1)
		/sizeof(asn_DEF_DefineEventCondition_Request_tags_1[0]), /* 1 */
	asn_DEF_DefineEventCondition_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_DefineEventCondition_Request_tags_1)
		/sizeof(asn_DEF_DefineEventCondition_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DefineEventCondition_Request_1,
	7,	/* Elements count */
	&asn_SPC_DefineEventCondition_Request_specs_1	/* Additional specs */
};

