/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "DefineEventAction-Request.h"

static asn_TYPE_member_t asn_MBR_listOfModifier_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Modifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_listOfModifier_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfModifier_specs_3 = {
	sizeof(struct DefineEventAction_Request__listOfModifier),
	offsetof(struct DefineEventAction_Request__listOfModifier, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfModifier_3 = {
	"listOfModifier",
	"listOfModifier",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfModifier_tags_3,
	sizeof(asn_DEF_listOfModifier_tags_3)
		/sizeof(asn_DEF_listOfModifier_tags_3[0]) - 1, /* 1 */
	asn_DEF_listOfModifier_tags_3,	/* Same as above */
	sizeof(asn_DEF_listOfModifier_tags_3)
		/sizeof(asn_DEF_listOfModifier_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfModifier_3,
	1,	/* Single element */
	&asn_SPC_listOfModifier_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DefineEventAction_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DefineEventAction_Request, eventActionName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventActionName"
		},
	{ ATF_POINTER, 1, offsetof(struct DefineEventAction_Request, listOfModifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfModifier_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfModifier"
		},
	{ ATF_POINTER, 0, offsetof(struct DefineEventAction_Request, confirmedServiceRequest),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ConfirmedServiceRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"confirmedServiceRequest"
		},
	{ ATF_POINTER, 1, offsetof(struct DefineEventAction_Request, cs_extension),
		(ASN_TAG_CLASS_CONTEXT | (79 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Request_Detail,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cs-extension"
		},
};
static ber_tlv_tag_t asn_DEF_DefineEventAction_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DefineEventAction_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventActionName at 2484 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* listOfModifier at 2485 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* confirmedServiceRequest at 2486 */
    { (ASN_TAG_CLASS_CONTEXT | (79 << 2)), 3, 0, 0 } /* cs-extension at 2487 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DefineEventAction_Request_specs_1 = {
	sizeof(struct DefineEventAction_Request),
	offsetof(struct DefineEventAction_Request, _asn_ctx),
	asn_MAP_DefineEventAction_Request_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DefineEventAction_Request = {
	"DefineEventAction-Request",
	"DefineEventAction-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DefineEventAction_Request_tags_1,
	sizeof(asn_DEF_DefineEventAction_Request_tags_1)
		/sizeof(asn_DEF_DefineEventAction_Request_tags_1[0]), /* 1 */
	asn_DEF_DefineEventAction_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_DefineEventAction_Request_tags_1)
		/sizeof(asn_DEF_DefineEventAction_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DefineEventAction_Request_1,
	4,	/* Elements count */
	&asn_SPC_DefineEventAction_Request_specs_1	/* Additional specs */
};

