/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "DeleteNamedVariableList-Request.h"

static int
memb_scopeOfDelete_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int asn_DFL_2_set_0(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		*st = 0;
		return 0;
	} else {
		/* Test default value 0 */
		return (*st == 0);
	}
}
static asn_TYPE_member_t asn_MBR_listOfVariableListName_7[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_listOfVariableListName_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfVariableListName_specs_7 = {
	sizeof(struct DeleteNamedVariableList_Request__listOfVariableListName),
	offsetof(struct DeleteNamedVariableList_Request__listOfVariableListName, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfVariableListName_7 = {
	"listOfVariableListName",
	"listOfVariableListName",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfVariableListName_tags_7,
	sizeof(asn_DEF_listOfVariableListName_tags_7)
		/sizeof(asn_DEF_listOfVariableListName_tags_7[0]) - 1, /* 1 */
	asn_DEF_listOfVariableListName_tags_7,	/* Same as above */
	sizeof(asn_DEF_listOfVariableListName_tags_7)
		/sizeof(asn_DEF_listOfVariableListName_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfVariableListName_7,
	1,	/* Single element */
	&asn_SPC_listOfVariableListName_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DeleteNamedVariableList_Request_1[] = {
	{ ATF_NOFLAGS, 3, offsetof(struct DeleteNamedVariableList_Request, scopeOfDelete),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_scopeOfDelete_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_2_set_0,	/* DEFAULT 0 */
		"scopeOfDelete"
		},
	{ ATF_POINTER, 2, offsetof(struct DeleteNamedVariableList_Request, listOfVariableListName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfVariableListName_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfVariableListName"
		},
	{ ATF_POINTER, 1, offsetof(struct DeleteNamedVariableList_Request, domainName),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"domainName"
		},
};
static ber_tlv_tag_t asn_DEF_DeleteNamedVariableList_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DeleteNamedVariableList_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scopeOfDelete at 2139 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* listOfVariableListName at 2141 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* domainName at 2142 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DeleteNamedVariableList_Request_specs_1 = {
	sizeof(struct DeleteNamedVariableList_Request),
	offsetof(struct DeleteNamedVariableList_Request, _asn_ctx),
	asn_MAP_DeleteNamedVariableList_Request_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DeleteNamedVariableList_Request = {
	"DeleteNamedVariableList-Request",
	"DeleteNamedVariableList-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DeleteNamedVariableList_Request_tags_1,
	sizeof(asn_DEF_DeleteNamedVariableList_Request_tags_1)
		/sizeof(asn_DEF_DeleteNamedVariableList_Request_tags_1[0]), /* 1 */
	asn_DEF_DeleteNamedVariableList_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_DeleteNamedVariableList_Request_tags_1)
		/sizeof(asn_DEF_DeleteNamedVariableList_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DeleteNamedVariableList_Request_1,
	3,	/* Elements count */
	&asn_SPC_DeleteNamedVariableList_Request_specs_1	/* Additional specs */
};

