/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-Object-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_DomainState_H_
#define	_DomainState_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DomainState {
	DomainState_non_existent	= 0,
	DomainState_loading	= 1,
	DomainState_ready	= 2,
	DomainState_in_use	= 3,
	DomainState_complete	= 4,
	DomainState_incomplete	= 5,
	DomainState_d1	= 7,
	DomainState_d2	= 8,
	DomainState_d3	= 9,
	DomainState_d4	= 10,
	DomainState_d5	= 11,
	DomainState_d6	= 12,
	DomainState_d7	= 13,
	DomainState_d8	= 14,
	DomainState_d9	= 15
} e_DomainState;

/* DomainState */
typedef long	 DomainState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DomainState;
asn_struct_free_f DomainState_free;
asn_struct_print_f DomainState_print;
asn_constr_check_f DomainState_constraint;
ber_type_decoder_f DomainState_decode_ber;
der_type_encoder_f DomainState_encode_der;
xer_type_decoder_f DomainState_decode_xer;
xer_type_encoder_f DomainState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DomainState_H_ */
