/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "Domain-instance.h"

static asn_TYPE_member_t asn_MBR_capabilities_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_MMSString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_capabilities_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_capabilities_specs_6 = {
	sizeof(struct Domain_instance__definition__details__capabilities),
	offsetof(struct Domain_instance__definition__details__capabilities, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_capabilities_6 = {
	"capabilities",
	"capabilities",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_capabilities_tags_6,
	sizeof(asn_DEF_capabilities_tags_6)
		/sizeof(asn_DEF_capabilities_tags_6[0]) - 1, /* 1 */
	asn_DEF_capabilities_tags_6,	/* Same as above */
	sizeof(asn_DEF_capabilities_tags_6)
		/sizeof(asn_DEF_capabilities_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_capabilities_6,
	1,	/* Single element */
	&asn_SPC_capabilities_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_programInvocations_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Program_Invocation_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_programInvocations_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_programInvocations_specs_11 = {
	sizeof(struct Domain_instance__definition__details__programInvocations),
	offsetof(struct Domain_instance__definition__details__programInvocations, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_programInvocations_11 = {
	"programInvocations",
	"programInvocations",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_programInvocations_tags_11,
	sizeof(asn_DEF_programInvocations_tags_11)
		/sizeof(asn_DEF_programInvocations_tags_11[0]) - 1, /* 1 */
	asn_DEF_programInvocations_tags_11,	/* Same as above */
	sizeof(asn_DEF_programInvocations_tags_11)
		/sizeof(asn_DEF_programInvocations_tags_11[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_programInvocations_11,
	1,	/* Single element */
	&asn_SPC_programInvocations_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_namedVariables_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Named_Variable_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_namedVariables_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_namedVariables_specs_13 = {
	sizeof(struct Domain_instance__definition__details__namedVariables),
	offsetof(struct Domain_instance__definition__details__namedVariables, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_namedVariables_13 = {
	"namedVariables",
	"namedVariables",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_namedVariables_tags_13,
	sizeof(asn_DEF_namedVariables_tags_13)
		/sizeof(asn_DEF_namedVariables_tags_13[0]) - 1, /* 1 */
	asn_DEF_namedVariables_tags_13,	/* Same as above */
	sizeof(asn_DEF_namedVariables_tags_13)
		/sizeof(asn_DEF_namedVariables_tags_13[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_namedVariables_13,
	1,	/* Single element */
	&asn_SPC_namedVariables_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_namedVariableLists_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Named_Variable_List_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_namedVariableLists_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_namedVariableLists_specs_15 = {
	sizeof(struct Domain_instance__definition__details__namedVariableLists),
	offsetof(struct Domain_instance__definition__details__namedVariableLists, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_namedVariableLists_15 = {
	"namedVariableLists",
	"namedVariableLists",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_namedVariableLists_tags_15,
	sizeof(asn_DEF_namedVariableLists_tags_15)
		/sizeof(asn_DEF_namedVariableLists_tags_15[0]) - 1, /* 1 */
	asn_DEF_namedVariableLists_tags_15,	/* Same as above */
	sizeof(asn_DEF_namedVariableLists_tags_15)
		/sizeof(asn_DEF_namedVariableLists_tags_15[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_namedVariableLists_15,
	1,	/* Single element */
	&asn_SPC_namedVariableLists_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_namedTypes_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Named_Type_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_namedTypes_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_namedTypes_specs_17 = {
	sizeof(struct Domain_instance__definition__details__namedTypes),
	offsetof(struct Domain_instance__definition__details__namedTypes, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_namedTypes_17 = {
	"namedTypes",
	"namedTypes",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_namedTypes_tags_17,
	sizeof(asn_DEF_namedTypes_tags_17)
		/sizeof(asn_DEF_namedTypes_tags_17[0]) - 1, /* 1 */
	asn_DEF_namedTypes_tags_17,	/* Same as above */
	sizeof(asn_DEF_namedTypes_tags_17)
		/sizeof(asn_DEF_namedTypes_tags_17[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_namedTypes_17,
	1,	/* Single element */
	&asn_SPC_namedTypes_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventConditions_19[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Event_Condition_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_eventConditions_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_eventConditions_specs_19 = {
	sizeof(struct Domain_instance__definition__details__eventConditions),
	offsetof(struct Domain_instance__definition__details__eventConditions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventConditions_19 = {
	"eventConditions",
	"eventConditions",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventConditions_tags_19,
	sizeof(asn_DEF_eventConditions_tags_19)
		/sizeof(asn_DEF_eventConditions_tags_19[0]) - 1, /* 1 */
	asn_DEF_eventConditions_tags_19,	/* Same as above */
	sizeof(asn_DEF_eventConditions_tags_19)
		/sizeof(asn_DEF_eventConditions_tags_19[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventConditions_19,
	1,	/* Single element */
	&asn_SPC_eventConditions_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventActions_21[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Event_Action_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_eventActions_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_eventActions_specs_21 = {
	sizeof(struct Domain_instance__definition__details__eventActions),
	offsetof(struct Domain_instance__definition__details__eventActions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventActions_21 = {
	"eventActions",
	"eventActions",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventActions_tags_21,
	sizeof(asn_DEF_eventActions_tags_21)
		/sizeof(asn_DEF_eventActions_tags_21[0]) - 1, /* 1 */
	asn_DEF_eventActions_tags_21,	/* Same as above */
	sizeof(asn_DEF_eventActions_tags_21)
		/sizeof(asn_DEF_eventActions_tags_21[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventActions_21,
	1,	/* Single element */
	&asn_SPC_eventActions_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventEnrollments_23[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Event_Enrollment_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_eventEnrollments_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_eventEnrollments_specs_23 = {
	sizeof(struct Domain_instance__definition__details__eventEnrollments),
	offsetof(struct Domain_instance__definition__details__eventEnrollments, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventEnrollments_23 = {
	"eventEnrollments",
	"eventEnrollments",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventEnrollments_tags_23,
	sizeof(asn_DEF_eventEnrollments_tags_23)
		/sizeof(asn_DEF_eventEnrollments_tags_23[0]) - 1, /* 1 */
	asn_DEF_eventEnrollments_tags_23,	/* Same as above */
	sizeof(asn_DEF_eventEnrollments_tags_23)
		/sizeof(asn_DEF_eventEnrollments_tags_23[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventEnrollments_23,
	1,	/* Single element */
	&asn_SPC_eventEnrollments_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventConditionLists_25[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Event_Condition_List_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_eventConditionLists_tags_25[] = {
	(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_eventConditionLists_specs_25 = {
	sizeof(struct Domain_instance__definition__details__eventConditionLists),
	offsetof(struct Domain_instance__definition__details__eventConditionLists, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventConditionLists_25 = {
	"eventConditionLists",
	"eventConditionLists",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventConditionLists_tags_25,
	sizeof(asn_DEF_eventConditionLists_tags_25)
		/sizeof(asn_DEF_eventConditionLists_tags_25[0]) - 1, /* 1 */
	asn_DEF_eventConditionLists_tags_25,	/* Same as above */
	sizeof(asn_DEF_eventConditionLists_tags_25)
		/sizeof(asn_DEF_eventConditionLists_tags_25[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventConditionLists_25,
	1,	/* Single element */
	&asn_SPC_eventConditionLists_specs_25	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_details_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, capabilities),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_capabilities_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"capabilities"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, state),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DomainState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"state"
		},
	{ ATF_POINTER, 0, offsetof(struct Domain_instance__definition__details, accessControl),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Access_Control_List_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessControl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, sharable),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sharable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, programInvocations),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_programInvocations_11,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"programInvocations"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, namedVariables),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_namedVariables_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"namedVariables"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, namedVariableLists),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		0,
		&asn_DEF_namedVariableLists_15,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"namedVariableLists"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, namedTypes),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		0,
		&asn_DEF_namedTypes_17,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"namedTypes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, eventConditions),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		0,
		&asn_DEF_eventConditions_19,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventConditions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, eventActions),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		0,
		&asn_DEF_eventActions_21,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventActions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, eventEnrollments),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		0,
		&asn_DEF_eventEnrollments_23,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventEnrollments"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition__details, eventConditionLists),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		0,
		&asn_DEF_eventConditionLists_25,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventConditionLists"
		},
};
static ber_tlv_tag_t asn_DEF_details_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_details_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* capabilities at 2924 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* state at 2926 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* accessControl at 2929 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 3, 0, 0 }, /* sharable at 2930 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 4, 0, 0 }, /* programInvocations at 2933 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 5, 0, 0 }, /* namedVariables at 2937 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 6, 0, 0 }, /* namedVariableLists at 2940 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 7, 0, 0 }, /* namedTypes at 2943 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 8, 0, 0 }, /* eventConditions at 2946 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 9, 0, 0 }, /* eventActions at 2949 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 10, 0, 0 }, /* eventEnrollments at 2952 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 11, 0, 0 } /* eventConditionLists at 2955 */
};
static asn_SEQUENCE_specifics_t asn_SPC_details_specs_5 = {
	sizeof(struct Domain_instance__definition__details),
	offsetof(struct Domain_instance__definition__details, _asn_ctx),
	asn_MAP_details_tag2el_5,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_details_5 = {
	"details",
	"details",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_details_tags_5,
	sizeof(asn_DEF_details_tags_5)
		/sizeof(asn_DEF_details_tags_5[0]) - 1, /* 1 */
	asn_DEF_details_tags_5,	/* Same as above */
	sizeof(asn_DEF_details_tags_5)
		/sizeof(asn_DEF_details_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_details_5,
	12,	/* Elements count */
	&asn_SPC_details_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_definition_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition, choice.reference),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reference"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance__definition, choice.details),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_details_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"details"
		},
};
static asn_TYPE_tag2member_t asn_MAP_definition_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* reference at 2921 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* details at 2924 */
};
static asn_CHOICE_specifics_t asn_SPC_definition_specs_3 = {
	sizeof(struct Domain_instance__definition),
	offsetof(struct Domain_instance__definition, _asn_ctx),
	offsetof(struct Domain_instance__definition, present),
	sizeof(((struct Domain_instance__definition *)0)->present),
	asn_MAP_definition_tag2el_3,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_definition_3 = {
	"definition",
	"definition",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_definition_3,
	2,	/* Elements count */
	&asn_SPC_definition_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Domain_instance_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance, name),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Domain_instance, definition),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_definition_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"definition"
		},
};
static ber_tlv_tag_t asn_DEF_Domain_instance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Domain_instance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* name at 2919 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reference at 2921 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* details at 2924 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Domain_instance_specs_1 = {
	sizeof(struct Domain_instance),
	offsetof(struct Domain_instance, _asn_ctx),
	asn_MAP_Domain_instance_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Domain_instance = {
	"Domain-instance",
	"Domain-instance",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Domain_instance_tags_1,
	sizeof(asn_DEF_Domain_instance_tags_1)
		/sizeof(asn_DEF_Domain_instance_tags_1[0]), /* 1 */
	asn_DEF_Domain_instance_tags_1,	/* Same as above */
	sizeof(asn_DEF_Domain_instance_tags_1)
		/sizeof(asn_DEF_Domain_instance_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Domain_instance_1,
	2,	/* Elements count */
	&asn_SPC_Domain_instance_specs_1	/* Additional specs */
};

