/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_EE_State_H_
#define	_EE_State_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EE_State {
	EE_State_disabled	= 0,
	EE_State_idle	= 1,
	EE_State_active	= 2,
	EE_State_activeNoAckA	= 3,
	EE_State_idleNoAckI	= 4,
	EE_State_idleNoAckA	= 5,
	EE_State_idleAcked	= 6,
	EE_State_activeAcked	= 7,
	EE_State_undefined	= 8
} e_EE_State;

/* EE-State */
typedef long	 EE_State_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EE_State;
asn_struct_free_f EE_State_free;
asn_struct_print_f EE_State_print;
asn_constr_check_f EE_State_constraint;
ber_type_decoder_f EE_State_decode_ber;
der_type_encoder_f EE_State_encode_der;
xer_type_decoder_f EE_State_decode_xer;
xer_type_encoder_f EE_State_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EE_State_H_ */
