/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_EN_Additional_Detail_H_
#define	_EN_Additional_Detail_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VisibleString.h"
#include "NativeInteger.h"
#include "NULL.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EN_Additional_Detail_PR {
	EN_Additional_Detail_PR_NOTHING,	/* No components present */
	EN_Additional_Detail_PR_string,
	EN_Additional_Detail_PR_index,
	EN_Additional_Detail_PR_noEnhancement
} EN_Additional_Detail_PR;

/* EN-Additional-Detail */
typedef struct EN_Additional_Detail {
	EN_Additional_Detail_PR present;
	union EN_Additional_Detail_u {
		VisibleString_t	 string;
		long	 index;
		NULL_t	 noEnhancement;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EN_Additional_Detail_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EN_Additional_Detail;

#ifdef __cplusplus
}
#endif

#endif	/* _EN_Additional_Detail_H_ */
