/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Event_Condition_List_instance_H_
#define	_Event_Condition_List_instance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectName.h"
#include "OBJECT_IDENTIFIER.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Event_Condition_List_instance__definition_PR {
	Event_Condition_List_instance__definition_PR_NOTHING,	/* No components present */
	Event_Condition_List_instance__definition_PR_reference,
	Event_Condition_List_instance__definition_PR_details
} Event_Condition_List_instance__definition_PR;

/* Forward declarations */
struct Access_Control_List_instance;
struct Event_Condition_instance;
struct Event_Condition_List_instance;

/* Event-Condition-List-instance */
typedef struct Event_Condition_List_instance {
	ObjectName_t	 name;
	struct Event_Condition_List_instance__definition {
		Event_Condition_List_instance__definition_PR present;
		union Event_Condition_List_instance__definition_u {
			OBJECT_IDENTIFIER_t	 reference;
			struct Event_Condition_List_instance__definition__details {
				struct Access_Control_List_instance	*accessControl;
				struct Event_Condition_List_instance__definition__details__eventConditions {
					A_SEQUENCE_OF(struct Event_Condition_instance) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} eventConditions;
				struct Event_Condition_List_instance__definition__details__eventConditionLists {
					A_SEQUENCE_OF(struct Event_Condition_List_instance) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} eventConditionLists;
				struct Event_Condition_List_instance__definition__details__referencingEventConditionLists {
					A_SEQUENCE_OF(struct Event_Condition_List_instance) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} referencingEventConditionLists;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} details;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} definition;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Event_Condition_List_instance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Event_Condition_List_instance;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Access-Control-List-instance.h"
#include "Event-Condition-instance.h"
#include "Event-Condition-List-instance.h"

#endif	/* _Event_Condition_List_instance_H_ */
