/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1A"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_FileRead_Response_H_
#define	_FileRead_Response_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FileRead-Response */
typedef struct FileRead_Response {
	OCTET_STRING_t	 fileData;
	BOOLEAN_t	*moreFollows	/* DEFAULT TRUE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileRead_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileRead_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _FileRead_Response_H_ */
