/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_GeneralManagementParameters_H_
#define	_GeneralManagementParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MMSString.h"
#include "NativeInteger.h"
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GeneralManagementParameters */
typedef struct GeneralManagementParameters {
	MMSString_t	 localDetail;
	struct GeneralManagementParameters__supportForTime {
		BOOLEAN_t	 timeOfDay;
		BOOLEAN_t	 timeSequence;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} supportForTime;
	long	 granularityOfTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeneralManagementParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeneralManagementParameters;

#ifdef __cplusplus
}
#endif

#endif	/* _GeneralManagementParameters_H_ */
