/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_GetAccessControlListAttributes_Response_H_
#define	_GetAccessControlListAttributes_Response_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier.h"
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"
#include "asn_SEQUENCE_OF.h"
#include "ObjectClass.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AccessCondition;

/* GetAccessControlListAttributes-Response */
typedef struct GetAccessControlListAttributes_Response {
	Identifier_t	 name;
	struct GetAccessControlListAttributes_Response__accessControlListElements {
		struct AccessCondition	*readAccessCondition	/* OPTIONAL */;
		struct AccessCondition	*storeAccessCondition	/* OPTIONAL */;
		struct AccessCondition	*writeAccessCondition	/* OPTIONAL */;
		struct AccessCondition	*loadAccessCondition	/* OPTIONAL */;
		struct AccessCondition	*executeAccessCondition	/* OPTIONAL */;
		struct AccessCondition	*deleteAccessCondition	/* OPTIONAL */;
		struct AccessCondition	*editAccessCondition	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} accessControlListElements;
	BOOLEAN_t	 vMDuse;
	struct GetAccessControlListAttributes_Response__references {
		A_SEQUENCE_OF(struct GetAccessControlListAttributes_Response__references__Member {
			ObjectClass_t	 objectClass;
			long	 objectCount;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} references;
	Identifier_t	*accessControlList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAccessControlListAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetAccessControlListAttributes_Response;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AccessCondition.h"

#endif	/* _GetAccessControlListAttributes_Response_H_ */
