/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_GetAlarmSummary_Response_H_
#define	_GetAlarmSummary_Response_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlarmSummary;

/* GetAlarmSummary-Response */
typedef struct GetAlarmSummary_Response {
	struct GetAlarmSummary_Response__listOfAlarmSummary {
		A_SEQUENCE_OF(struct AlarmSummary) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfAlarmSummary;
	BOOLEAN_t	*moreFollows	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAlarmSummary_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetAlarmSummary_Response;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlarmSummary.h"

#endif	/* _GetAlarmSummary_Response_H_ */
