/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_GetCapabilityList_Request_H_
#define	_GetCapabilityList_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MMSString.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetCapabilityList-Request */
typedef struct GetCapabilityList_Request {
	MMSString_t	*continueAfter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetCapabilityList_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetCapabilityList_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _GetCapabilityList_Request_H_ */
