/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "GetDataExchangeAttributes-Response.h"

static asn_TYPE_member_t asn_MBR_listOfRequestTypeDescriptions_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_TypeDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_listOfRequestTypeDescriptions_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfRequestTypeDescriptions_specs_3 = {
	sizeof(struct GetDataExchangeAttributes_Response__listOfRequestTypeDescriptions),
	offsetof(struct GetDataExchangeAttributes_Response__listOfRequestTypeDescriptions, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfRequestTypeDescriptions_3 = {
	"listOfRequestTypeDescriptions",
	"listOfRequestTypeDescriptions",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfRequestTypeDescriptions_tags_3,
	sizeof(asn_DEF_listOfRequestTypeDescriptions_tags_3)
		/sizeof(asn_DEF_listOfRequestTypeDescriptions_tags_3[0]) - 1, /* 1 */
	asn_DEF_listOfRequestTypeDescriptions_tags_3,	/* Same as above */
	sizeof(asn_DEF_listOfRequestTypeDescriptions_tags_3)
		/sizeof(asn_DEF_listOfRequestTypeDescriptions_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfRequestTypeDescriptions_3,
	1,	/* Single element */
	&asn_SPC_listOfRequestTypeDescriptions_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_listOfResponseTypeDescriptions_5[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_TypeDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_listOfResponseTypeDescriptions_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfResponseTypeDescriptions_specs_5 = {
	sizeof(struct GetDataExchangeAttributes_Response__listOfResponseTypeDescriptions),
	offsetof(struct GetDataExchangeAttributes_Response__listOfResponseTypeDescriptions, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfResponseTypeDescriptions_5 = {
	"listOfResponseTypeDescriptions",
	"listOfResponseTypeDescriptions",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfResponseTypeDescriptions_tags_5,
	sizeof(asn_DEF_listOfResponseTypeDescriptions_tags_5)
		/sizeof(asn_DEF_listOfResponseTypeDescriptions_tags_5[0]) - 1, /* 1 */
	asn_DEF_listOfResponseTypeDescriptions_tags_5,	/* Same as above */
	sizeof(asn_DEF_listOfResponseTypeDescriptions_tags_5)
		/sizeof(asn_DEF_listOfResponseTypeDescriptions_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfResponseTypeDescriptions_5,
	1,	/* Single element */
	&asn_SPC_listOfResponseTypeDescriptions_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_GetDataExchangeAttributes_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetDataExchangeAttributes_Response, inUse),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"inUse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetDataExchangeAttributes_Response, listOfRequestTypeDescriptions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfRequestTypeDescriptions_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfRequestTypeDescriptions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetDataExchangeAttributes_Response, listOfResponseTypeDescriptions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_listOfResponseTypeDescriptions_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfResponseTypeDescriptions"
		},
	{ ATF_POINTER, 2, offsetof(struct GetDataExchangeAttributes_Response, programInvocation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"programInvocation"
		},
	{ ATF_POINTER, 1, offsetof(struct GetDataExchangeAttributes_Response, accessControlList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessControlList"
		},
};
static ber_tlv_tag_t asn_DEF_GetDataExchangeAttributes_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GetDataExchangeAttributes_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* inUse at 2188 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* listOfRequestTypeDescriptions at 2189 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* listOfResponseTypeDescriptions at 2190 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* programInvocation at 2191 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* accessControlList at 2192 */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetDataExchangeAttributes_Response_specs_1 = {
	sizeof(struct GetDataExchangeAttributes_Response),
	offsetof(struct GetDataExchangeAttributes_Response, _asn_ctx),
	asn_MAP_GetDataExchangeAttributes_Response_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GetDataExchangeAttributes_Response = {
	"GetDataExchangeAttributes-Response",
	"GetDataExchangeAttributes-Response",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GetDataExchangeAttributes_Response_tags_1,
	sizeof(asn_DEF_GetDataExchangeAttributes_Response_tags_1)
		/sizeof(asn_DEF_GetDataExchangeAttributes_Response_tags_1[0]), /* 1 */
	asn_DEF_GetDataExchangeAttributes_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetDataExchangeAttributes_Response_tags_1)
		/sizeof(asn_DEF_GetDataExchangeAttributes_Response_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GetDataExchangeAttributes_Response_1,
	5,	/* Elements count */
	&asn_SPC_GetDataExchangeAttributes_Response_specs_1	/* Additional specs */
};

