/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_GetEventEnrollmentAttributes_Request_H_
#define	_GetEventEnrollmentAttributes_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetEventEnrollmentAttributes_Request__scopeOfRequest {
	GetEventEnrollmentAttributes_Request__scopeOfRequest_specific	= 0,
	GetEventEnrollmentAttributes_Request__scopeOfRequest_client	= 1,
	GetEventEnrollmentAttributes_Request__scopeOfRequest_ec	= 2,
	GetEventEnrollmentAttributes_Request__scopeOfRequest_ea	= 3
} e_GetEventEnrollmentAttributes_Request__scopeOfRequest;

/* Forward declarations */
struct ApplicationReference;
struct ObjectName;

/* GetEventEnrollmentAttributes-Request */
typedef struct GetEventEnrollmentAttributes_Request {
	long	*scopeOfRequest	/* DEFAULT 1 */;
	struct GetEventEnrollmentAttributes_Request__eventEnrollmentNames {
		A_SEQUENCE_OF(struct ObjectName) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *eventEnrollmentNames;
	struct ApplicationReference	*clientApplication	/* OPTIONAL */;
	struct ObjectName	*eventConditionName	/* OPTIONAL */;
	struct ObjectName	*eventActionName	/* OPTIONAL */;
	struct ObjectName	*continueAfter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetEventEnrollmentAttributes_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetEventEnrollmentAttributes_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ApplicationReference.h"
#include "ObjectName.h"

#endif	/* _GetEventEnrollmentAttributes_Request_H_ */
