/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_GetNamedTypeAttributes_Response_H_
#define	_GetNamedTypeAttributes_Response_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "TypeSpecification.h"
#include "Identifier.h"
#include "VisibleString.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetNamedTypeAttributes-Response */
typedef struct GetNamedTypeAttributes_Response {
	BOOLEAN_t	 mmsDeletable;
	TypeSpecification_t	 typeSpecification;
	Identifier_t	*accessControlList	/* OPTIONAL */;
	VisibleString_t	*meaning	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetNamedTypeAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetNamedTypeAttributes_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _GetNamedTypeAttributes_Response_H_ */
