/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_GetReferenceRequestPdu_H_
#define	_GetReferenceRequestPdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VisibleString.h"
#include "NativeInteger.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetReferenceRequestPdu */
typedef struct GetReferenceRequestPdu {
	VisibleString_t	 ident;
	struct GetReferenceRequestPdu__offset {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} offset;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetReferenceRequestPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetReferenceRequestPdu;

#ifdef __cplusplus
}
#endif

#endif	/* _GetReferenceRequestPdu_H_ */
