/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "GetVariableAccessAttributes-Response.h"

static asn_TYPE_member_t asn_MBR_GetVariableAccessAttributes_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetVariableAccessAttributes_Response, mmsDeletable),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mmsDeletable"
		},
	{ ATF_POINTER, 1, offsetof(struct GetVariableAccessAttributes_Response, address),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Address,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"address"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetVariableAccessAttributes_Response, typeDescription),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"typeDescription"
		},
	{ ATF_POINTER, 2, offsetof(struct GetVariableAccessAttributes_Response, accessControlList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessControlList"
		},
	{ ATF_POINTER, 1, offsetof(struct GetVariableAccessAttributes_Response, meaning),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"meaning"
		},
};
static ber_tlv_tag_t asn_DEF_GetVariableAccessAttributes_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GetVariableAccessAttributes_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mmsDeletable at 2088 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* address at 2089 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* typeDescription at 2090 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* accessControlList at 2091 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* meaning at 2093 */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetVariableAccessAttributes_Response_specs_1 = {
	sizeof(struct GetVariableAccessAttributes_Response),
	offsetof(struct GetVariableAccessAttributes_Response, _asn_ctx),
	asn_MAP_GetVariableAccessAttributes_Response_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GetVariableAccessAttributes_Response = {
	"GetVariableAccessAttributes-Response",
	"GetVariableAccessAttributes-Response",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GetVariableAccessAttributes_Response_tags_1,
	sizeof(asn_DEF_GetVariableAccessAttributes_Response_tags_1)
		/sizeof(asn_DEF_GetVariableAccessAttributes_Response_tags_1[0]), /* 1 */
	asn_DEF_GetVariableAccessAttributes_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetVariableAccessAttributes_Response_tags_1)
		/sizeof(asn_DEF_GetVariableAccessAttributes_Response_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GetVariableAccessAttributes_Response_1,
	5,	/* Elements count */
	&asn_SPC_GetVariableAccessAttributes_Response_specs_1	/* Additional specs */
};

