/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_GSEMngtResponsePdu_H_
#define	_GSEMngtResponsePdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VisibleString.h"
#include "NativeInteger.h"
#include "GlbErrors.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GSEMngtResponsePdu__response_PR {
	GSEMngtResponsePdu__response_PR_NOTHING,	/* No components present */
	GSEMngtResponsePdu__response_PR_responsePositive,
	GSEMngtResponsePdu__response_PR_responseNegative
} GSEMngtResponsePdu__response_PR;

/* Forward declarations */
struct RequestResults;

/* GSEMngtResponsePdu */
typedef struct GSEMngtResponsePdu {
	VisibleString_t	 ident;
	long	*confRev	/* OPTIONAL */;
	struct GSEMngtResponsePdu__response {
		GSEMngtResponsePdu__response_PR present;
		union GSEMngtResponsePdu__response_u {
			struct GSEMngtResponsePdu__response__responsePositive {
				VisibleString_t	*datSet	/* OPTIONAL */;
				struct GSEMngtResponsePdu__response__responsePositive__result {
					A_SEQUENCE_OF(struct RequestResults) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} result;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} responsePositive;
			GlbErrors_t	 responseNegative;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} response;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GSEMngtResponsePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GSEMngtResponsePdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RequestResults.h"

#endif	/* _GSEMngtResponsePdu_H_ */
