/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_IECGoosePdu_H_
#define	_IECGoosePdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VisibleString.h"
#include "NativeInteger.h"
#include "UtcTime.h"
#include "BOOLEAN.h"
#include "OCTET_STRING.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data;

/* IECGoosePdu */
typedef struct IECGoosePdu {
	VisibleString_t	 gocbRef;
	long	 timeAllowedtoLive;
	VisibleString_t	 datSet;
	VisibleString_t	*goID	/* OPTIONAL */;
	UtcTime_t	 t;
	long	 stNum;
	long	 sqNum;
	BOOLEAN_t	*test	/* DEFAULT FALSE */;
	long	 confRev;
	BOOLEAN_t	*ndsCom	/* DEFAULT FALSE */;
	long	 numDatSetEntries;
	struct IECGoosePdu__allData {
		A_SEQUENCE_OF(struct Data) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} allData;
	OCTET_STRING_t	*security	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IECGoosePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IECGoosePdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _IECGoosePdu_H_ */
