/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "Journal-Entry-instance.h"

static int
informationType_7_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
informationType_7_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
informationType_7_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	informationType_7_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
informationType_7_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	informationType_7_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
informationType_7_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	informationType_7_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
informationType_7_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	informationType_7_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
informationType_7_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	informationType_7_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
informationType_7_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	informationType_7_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_INTEGER_enum_map_t asn_MAP_informationType_value2enum_7[] = {
	{ 0,	10,	"annotation" },
	{ 1,	10,	"event-data" },
	{ 2,	4,	"data" }
};
static unsigned int asn_MAP_informationType_enum2value_7[] = {
	0,	/* annotation(0) */
	2,	/* data(2) */
	1	/* event-data(1) */
};
static asn_INTEGER_specifics_t asn_SPC_informationType_specs_7 = {
	asn_MAP_informationType_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_informationType_enum2value_7,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_informationType_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_informationType_7 = {
	"informationType",
	"informationType",
	informationType_7_free,
	informationType_7_print,
	informationType_7_constraint,
	informationType_7_decode_ber,
	informationType_7_encode_der,
	informationType_7_decode_xer,
	informationType_7_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_informationType_tags_7,
	sizeof(asn_DEF_informationType_tags_7)
		/sizeof(asn_DEF_informationType_tags_7[0]) - 1, /* 1 */
	asn_DEF_informationType_tags_7,	/* Same as above */
	sizeof(asn_DEF_informationType_tags_7)
		/sizeof(asn_DEF_informationType_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_informationType_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventTransitionRecord_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance__eventTransitionRecord, name),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance__eventTransitionRecord, currentState),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EC_State,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"currentState"
		},
};
static ber_tlv_tag_t asn_DEF_eventTransitionRecord_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_eventTransitionRecord_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 0, 0, 0 }, /* name at 3251 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 1, 0, 0 } /* currentState at 3252 */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventTransitionRecord_specs_12 = {
	sizeof(struct Journal_Entry_instance__eventTransitionRecord),
	offsetof(struct Journal_Entry_instance__eventTransitionRecord, _asn_ctx),
	asn_MAP_eventTransitionRecord_tag2el_12,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventTransitionRecord_12 = {
	"eventTransitionRecord",
	"eventTransitionRecord",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventTransitionRecord_tags_12,
	sizeof(asn_DEF_eventTransitionRecord_tags_12)
		/sizeof(asn_DEF_eventTransitionRecord_tags_12[0]) - 1, /* 1 */
	asn_DEF_eventTransitionRecord_tags_12,	/* Same as above */
	sizeof(asn_DEF_eventTransitionRecord_tags_12)
		/sizeof(asn_DEF_eventTransitionRecord_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventTransitionRecord_12,
	2,	/* Elements count */
	&asn_SPC_eventTransitionRecord_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance__journalVariables__Member, variableTag),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MMS255String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"variableTag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance__journalVariables__Member, valueSpecification),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"valueSpecification"
		},
};
static ber_tlv_tag_t asn_DEF_Member_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Member_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 0, 0, 0 }, /* variableTag at 3257 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 1, 0, 0 } /* valueSpecification at 3258 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_16 = {
	sizeof(struct Journal_Entry_instance__journalVariables__Member),
	offsetof(struct Journal_Entry_instance__journalVariables__Member, _asn_ctx),
	asn_MAP_Member_tag2el_16,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_16 = {
	"SEQUENCE",
	"SEQUENCE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Member_tags_16,
	sizeof(asn_DEF_Member_tags_16)
		/sizeof(asn_DEF_Member_tags_16[0]), /* 1 */
	asn_DEF_Member_tags_16,	/* Same as above */
	sizeof(asn_DEF_Member_tags_16)
		/sizeof(asn_DEF_Member_tags_16[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Member_16,
	2,	/* Elements count */
	&asn_SPC_Member_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_journalVariables_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_16,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_journalVariables_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_journalVariables_specs_15 = {
	sizeof(struct Journal_Entry_instance__journalVariables),
	offsetof(struct Journal_Entry_instance__journalVariables, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_journalVariables_15 = {
	"journalVariables",
	"journalVariables",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_journalVariables_tags_15,
	sizeof(asn_DEF_journalVariables_tags_15)
		/sizeof(asn_DEF_journalVariables_tags_15[0]) - 1, /* 1 */
	asn_DEF_journalVariables_tags_15,	/* Same as above */
	sizeof(asn_DEF_journalVariables_tags_15)
		/sizeof(asn_DEF_journalVariables_tags_15[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_journalVariables_15,
	1,	/* Single element */
	&asn_SPC_journalVariables_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Journal_Entry_instance_1[] = {
	{ ATF_POINTER, 0, offsetof(struct Journal_Entry_instance, journal),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Journal_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"journal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance, entry),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"entry"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance, clientApplication),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApplicationReference,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"clientApplication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance, timeStamp),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeOfDay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeStamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance, orderOfReceipt),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"orderOfReceipt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Journal_Entry_instance, informationType),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_informationType_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"informationType"
		},
	{ ATF_POINTER, 3, offsetof(struct Journal_Entry_instance, textComment),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MMS255String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"textComment"
		},
	{ ATF_POINTER, 2, offsetof(struct Journal_Entry_instance, eventTransitionRecord),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_eventTransitionRecord_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventTransitionRecord"
		},
	{ ATF_POINTER, 1, offsetof(struct Journal_Entry_instance, journalVariables),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		0,
		&asn_DEF_journalVariables_15,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"journalVariables"
		},
};
static ber_tlv_tag_t asn_DEF_Journal_Entry_instance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Journal_Entry_instance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* journal at 3239 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* entry at 3240 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* clientApplication at 3241 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* timeStamp at 3242 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* orderOfReceipt at 3243 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* informationType at 3244 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* textComment at 3247 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* eventTransitionRecord at 3251 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 8, 0, 0 } /* journalVariables at 3258 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Journal_Entry_instance_specs_1 = {
	sizeof(struct Journal_Entry_instance),
	offsetof(struct Journal_Entry_instance, _asn_ctx),
	asn_MAP_Journal_Entry_instance_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Journal_Entry_instance = {
	"Journal-Entry-instance",
	"Journal-Entry-instance",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Journal_Entry_instance_tags_1,
	sizeof(asn_DEF_Journal_Entry_instance_tags_1)
		/sizeof(asn_DEF_Journal_Entry_instance_tags_1[0]), /* 1 */
	asn_DEF_Journal_Entry_instance_tags_1,	/* Same as above */
	sizeof(asn_DEF_Journal_Entry_instance_tags_1)
		/sizeof(asn_DEF_Journal_Entry_instance_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Journal_Entry_instance_1,
	9,	/* Elements count */
	&asn_SPC_Journal_Entry_instance_specs_1	/* Additional specs */
};

