/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_LoadData_H_
#define	_LoadData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoadData_PR {
	LoadData_PR_NOTHING,	/* No components present */
	LoadData_PR_non_coded
} LoadData_PR;

/* LoadData */
typedef struct LoadData {
	LoadData_PR present;
	union LoadData_u {
		OCTET_STRING_t	 non_coded;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadData;

#ifdef __cplusplus
}
#endif

#endif	/* _LoadData_H_ */
