/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "LoadUnitControlFromFile-Error.h"

static asn_TYPE_member_t asn_MBR_LoadUnitControlFromFile_Error_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LoadUnitControlFromFile_Error, choice.none),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"none"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LoadUnitControlFromFile_Error, choice.domain),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"domain"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LoadUnitControlFromFile_Error, choice.programInvocation),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"programInvocation"
		},
};
static asn_TYPE_tag2member_t asn_MAP_LoadUnitControlFromFile_Error_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* none at 1960 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* domain at 1961 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* programInvocation at 1962 */
};
static asn_CHOICE_specifics_t asn_SPC_LoadUnitControlFromFile_Error_specs_1 = {
	sizeof(struct LoadUnitControlFromFile_Error),
	offsetof(struct LoadUnitControlFromFile_Error, _asn_ctx),
	offsetof(struct LoadUnitControlFromFile_Error, present),
	sizeof(((struct LoadUnitControlFromFile_Error *)0)->present),
	asn_MAP_LoadUnitControlFromFile_Error_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LoadUnitControlFromFile_Error = {
	"LoadUnitControlFromFile-Error",
	"LoadUnitControlFromFile-Error",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_LoadUnitControlFromFile_Error_1,
	3,	/* Elements count */
	&asn_SPC_LoadUnitControlFromFile_Error_specs_1	/* Additional specs */
};

