/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-Object-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "Modifier.h"

static asn_TYPE_member_t asn_MBR_Modifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Modifier, choice.eventModifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AttachToEventCondition,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventModifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Modifier, choice.semaphoreModifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AttachToSemaphore,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"semaphoreModifier"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Modifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventModifier at 218 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* semaphoreModifier at 219 */
};
static asn_CHOICE_specifics_t asn_SPC_Modifier_specs_1 = {
	sizeof(struct Modifier),
	offsetof(struct Modifier, _asn_ctx),
	offsetof(struct Modifier, present),
	sizeof(((struct Modifier *)0)->present),
	asn_MAP_Modifier_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Modifier = {
	"Modifier",
	"Modifier",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Modifier_1,
	2,	/* Elements count */
	&asn_SPC_Modifier_specs_1	/* Additional specs */
};

