/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Named_Variable_List_instance_H_
#define	_Named_Variable_List_instance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectName.h"
#include "OBJECT_IDENTIFIER.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Named_Variable_List_instance__definition_PR {
	Named_Variable_List_instance__definition_PR_NOTHING,	/* No components present */
	Named_Variable_List_instance__definition_PR_reference,
	Named_Variable_List_instance__definition_PR_details
} Named_Variable_List_instance__definition_PR;

/* Forward declarations */
struct Access_Control_List_instance;
struct Variable_List_Item_instance;

/* Named-Variable-List-instance */
typedef struct Named_Variable_List_instance {
	ObjectName_t	 name;
	struct Named_Variable_List_instance__definition {
		Named_Variable_List_instance__definition_PR present;
		union Named_Variable_List_instance__definition_u {
			OBJECT_IDENTIFIER_t	 reference;
			struct Named_Variable_List_instance__definition__details {
				struct Access_Control_List_instance	*accessControl;
				struct Named_Variable_List_instance__definition__details__listOfVariables {
					A_SEQUENCE_OF(struct Variable_List_Item_instance) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} listOfVariables;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} details;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} definition;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Named_Variable_List_instance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Named_Variable_List_instance;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Access-Control-List-instance.h"
#include "Variable-List-Item-instance.h"

#endif	/* _Named_Variable_List_instance_H_ */
