/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Output_Request_H_
#define	_Output_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier.h"
#include "MMSString.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Output-Request */
typedef struct Output_Request {
	Identifier_t	 operatorStationName;
	struct Output_Request__listOfOutputData {
		A_SEQUENCE_OF(MMSString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfOutputData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Output_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Output_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _Output_Request_H_ */
