/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "ReportAccessControlledObjects-Request.h"

static asn_TYPE_member_t asn_MBR_ReportAccessControlledObjects_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportAccessControlledObjects_Request, accessControlList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessControlList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportAccessControlledObjects_Request, objectClass),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectClass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objectClass"
		},
	{ ATF_POINTER, 1, offsetof(struct ReportAccessControlledObjects_Request, continueAfter),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"continueAfter"
		},
};
static ber_tlv_tag_t asn_DEF_ReportAccessControlledObjects_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReportAccessControlledObjects_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* accessControlList at 1527 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* objectClass at 1528 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* continueAfter at 1529 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReportAccessControlledObjects_Request_specs_1 = {
	sizeof(struct ReportAccessControlledObjects_Request),
	offsetof(struct ReportAccessControlledObjects_Request, _asn_ctx),
	asn_MAP_ReportAccessControlledObjects_Request_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReportAccessControlledObjects_Request = {
	"ReportAccessControlledObjects-Request",
	"ReportAccessControlledObjects-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ReportAccessControlledObjects_Request_tags_1,
	sizeof(asn_DEF_ReportAccessControlledObjects_Request_tags_1)
		/sizeof(asn_DEF_ReportAccessControlledObjects_Request_tags_1[0]), /* 1 */
	asn_DEF_ReportAccessControlledObjects_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReportAccessControlledObjects_Request_tags_1)
		/sizeof(asn_DEF_ReportAccessControlledObjects_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ReportAccessControlledObjects_Request_1,
	3,	/* Elements count */
	&asn_SPC_ReportAccessControlledObjects_Request_specs_1	/* Additional specs */
};

