/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "Request-Detail.h"

static asn_TYPE_member_t asn_MBR_Request_Detail_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Request_Detail, choice.otherRequests),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otherRequests"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Request_Detail, choice.createProgramInvocation),
		(ASN_TAG_CLASS_CONTEXT | (38 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CS_CreateProgramInvocation_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"createProgramInvocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Request_Detail, choice.start),
		(ASN_TAG_CLASS_CONTEXT | (40 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CS_Start_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"start"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Request_Detail, choice.resume),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CS_Resume_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resume"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Request_Detail, choice.defineEventCondition),
		(ASN_TAG_CLASS_CONTEXT | (47 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CS_DefineEventCondition_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"defineEventCondition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Request_Detail, choice.alterEventConditionMonitoring),
		(ASN_TAG_CLASS_CONTEXT | (51 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CS_AlterEventConditionMonitoring_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alterEventConditionMonitoring"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Request_Detail, choice.defineEventEnrollment),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CS_DefineEventEnrollment_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"defineEventEnrollment"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Request_Detail, choice.alterEventEnrollment),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CS_AlterEventEnrollment_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alterEventEnrollment"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Request_Detail_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 0 }, /* otherRequests at 1000 */
    { (ASN_TAG_CLASS_CONTEXT | (38 << 2)), 1, 0, 0 }, /* createProgramInvocation at 1002 */
    { (ASN_TAG_CLASS_CONTEXT | (40 << 2)), 2, 0, 0 }, /* start at 1003 */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 3, 0, 0 }, /* resume at 1004 */
    { (ASN_TAG_CLASS_CONTEXT | (47 << 2)), 4, 0, 0 }, /* defineEventCondition at 1005 */
    { (ASN_TAG_CLASS_CONTEXT | (51 << 2)), 5, 0, 0 }, /* alterEventConditionMonitoring at 1007 */
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 6, 0, 0 }, /* defineEventEnrollment at 1008 */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 7, 0, 0 } /* alterEventEnrollment at 1009 */
};
static asn_CHOICE_specifics_t asn_SPC_Request_Detail_specs_1 = {
	sizeof(struct Request_Detail),
	offsetof(struct Request_Detail, _asn_ctx),
	offsetof(struct Request_Detail, present),
	sizeof(((struct Request_Detail *)0)->present),
	asn_MAP_Request_Detail_tag2el_1,
	8,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Request_Detail = {
	"Request-Detail",
	"Request-Detail",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Request_Detail_1,
	8,	/* Elements count */
	&asn_SPC_Request_Detail_specs_1	/* Additional specs */
};

