/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_RequestResults_H_
#define	_RequestResults_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "IA5String.h"
#include "ErrorReason.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RequestResults_PR {
	RequestResults_PR_NOTHING,	/* No components present */
	RequestResults_PR_offset,
	RequestResults_PR_reference,
	RequestResults_PR_error
} RequestResults_PR;

/* RequestResults */
typedef struct RequestResults {
	RequestResults_PR present;
	union RequestResults_u {
		long	 offset;
		IA5String_t	 reference;
		ErrorReason_t	 error;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RequestResults_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestResults;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestResults_H_ */
