/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-Object-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Running_Mode_H_
#define	_Running_Mode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Running_Mode {
	Running_Mode_free_run	= 0,
	Running_Mode_cycle_limited	= 1,
	Running_Mode_step_limited	= 2
} e_Running_Mode;

/* Running-Mode */
typedef long	 Running_Mode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Running_Mode;
asn_struct_free_f Running_Mode_free;
asn_struct_print_f Running_Mode_print;
asn_constr_check_f Running_Mode_constraint;
ber_type_decoder_f Running_Mode_decode_ber;
der_type_encoder_f Running_Mode_encode_der;
xer_type_decoder_f Running_Mode_decode_xer;
xer_type_encoder_f Running_Mode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Running_Mode_H_ */
