/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1A"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_ScatteredAccessDescription_H_
#define	_ScatteredAccessDescription_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "Identifier.h"
#include "constr_SEQUENCE.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VariableSpecification;
struct AlternateAccess;

/* ScatteredAccessDescription */
typedef struct ScatteredAccessDescription {
	A_SEQUENCE_OF(struct ScatteredAccessDescription__Member {
		Identifier_t	*componentName	/* OPTIONAL */;
		struct VariableSpecification	*variableSpecification;
		struct AlternateAccess	*alternateAccess	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScatteredAccessDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScatteredAccessDescription;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariableSpecification.h"
#include "AlternateAccess.h"

#endif	/* _ScatteredAccessDescription_H_ */
