/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_SCI_Information_H_
#define	_SCI_Information_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VMD-File.h"
#include "Service-and-Parameter-CBBs.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SCI-Information */
typedef struct SCI_Information {
	VMD_File_t	 partOne;
	Service_and_Parameter_CBBs_t	 partTwo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCI_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCI_Information;

#ifdef __cplusplus
}
#endif

#endif	/* _SCI_Information_H_ */
