/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "SemaphoreEntry.h"

static int
memb_entryClass_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int asn_DFL_8_set_64(int set_value, void **sptr) {
	Priority_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 64 */
		*st = 64;
		return 0;
	} else {
		/* Test default value 64 */
		return (*st == 64);
	}
}
static asn_TYPE_member_t asn_MBR_SemaphoreEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SemaphoreEntry, entryID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"entryID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SemaphoreEntry, entryClass),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_entryClass_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"entryClass"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SemaphoreEntry, applicationReference),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ApplicationReference,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"applicationReference"
		},
	{ ATF_POINTER, 5, offsetof(struct SemaphoreEntry, namedToken),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"namedToken"
		},
	{ ATF_POINTER, 4, offsetof(struct SemaphoreEntry, priority),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Priority,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_8_set_64,	/* DEFAULT 64 */
		"priority"
		},
	{ ATF_POINTER, 3, offsetof(struct SemaphoreEntry, remainingTimeOut),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"remainingTimeOut"
		},
	{ ATF_POINTER, 2, offsetof(struct SemaphoreEntry, abortOnTimeOut),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"abortOnTimeOut"
		},
	{ ATF_POINTER, 1, offsetof(struct SemaphoreEntry, relinquishIfConnectionLost),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"relinquishIfConnectionLost"
		},
};
static ber_tlv_tag_t asn_DEF_SemaphoreEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SemaphoreEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* entryID at 2259 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* entryClass at 2261 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* applicationReference at 2262 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* namedToken at 2263 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* priority at 2264 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* remainingTimeOut at 2265 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* abortOnTimeOut at 2266 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* relinquishIfConnectionLost at 2267 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SemaphoreEntry_specs_1 = {
	sizeof(struct SemaphoreEntry),
	offsetof(struct SemaphoreEntry, _asn_ctx),
	asn_MAP_SemaphoreEntry_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SemaphoreEntry = {
	"SemaphoreEntry",
	"SemaphoreEntry",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SemaphoreEntry_tags_1,
	sizeof(asn_DEF_SemaphoreEntry_tags_1)
		/sizeof(asn_DEF_SemaphoreEntry_tags_1[0]), /* 1 */
	asn_DEF_SemaphoreEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_SemaphoreEntry_tags_1)
		/sizeof(asn_DEF_SemaphoreEntry_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SemaphoreEntry_1,
	8,	/* Elements count */
	&asn_SPC_SemaphoreEntry_specs_1	/* Additional specs */
};

