/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Service_and_Parameter_CBBs_H_
#define	_Service_and_Parameter_CBBs_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ServiceSupportOptions.h"
#include "ParameterSupportOptions.h"
#include "NativeInteger.h"
#include "AdditionalSupportOptions.h"
#include "AdditionalCBBOptions.h"
#include "GeneralManagementParameters.h"
#include "VMDSupportParameters.h"
#include "DomainManagementParameters.h"
#include "ProgramInvocationManagementParameters.h"
#include "VariableAccessParameters.h"
#include "DataParameters.h"
#include "SemaphoreManagementParameters.h"
#include "OperatorCommunicationParameters.h"
#include "ErrorParameters.h"
#include "FileManagementParameters.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Service-and-Parameter-CBBs */
typedef struct Service_and_Parameter_CBBs {
	ServiceSupportOptions_t	 services_Client;
	ServiceSupportOptions_t	 services_Server;
	ParameterSupportOptions_t	 parameters;
	long	 nest;
	AdditionalSupportOptions_t	 extendedServices_Client;
	AdditionalSupportOptions_t	 extendedServices_Server;
	AdditionalCBBOptions_t	 extendedParameters;
	GeneralManagementParameters_t	 generalManagement;
	VMDSupportParameters_t	 vMDSupport;
	DomainManagementParameters_t	 domainManagement;
	ProgramInvocationManagementParameters_t	 programInvocation;
	VariableAccessParameters_t	 variableAccess;
	DataParameters_t	 dataParameters;
	SemaphoreManagementParameters_t	 semaphoreManagement;
	OperatorCommunicationParameters_t	 operatorCommunication;
	ErrorParameters_t	 errors;
	FileManagementParameters_t	 fileManagement;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Service_and_Parameter_CBBs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Service_and_Parameter_CBBs;

#ifdef __cplusplus
}
#endif

#endif	/* _Service_and_Parameter_CBBs_H_ */
