/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_StartUnitControl_Request_H_
#define	_StartUnitControl_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier.h"
#include "MMSString.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StartUnitControl_Request__executionArgument_PR {
	StartUnitControl_Request__executionArgument_PR_NOTHING,	/* No components present */
	StartUnitControl_Request__executionArgument_PR_simpleString
} StartUnitControl_Request__executionArgument_PR;

/* StartUnitControl-Request */
typedef struct StartUnitControl_Request {
	Identifier_t	 unitControlName;
	struct StartUnitControl_Request__executionArgument {
		StartUnitControl_Request__executionArgument_PR present;
		union StartUnitControl_Request__executionArgument_u {
			MMSString_t	 simpleString;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *executionArgument;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StartUnitControl_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartUnitControl_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _StartUnitControl_Request_H_ */
