/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Start_Request_H_
#define	_Start_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier.h"
#include "MMSString.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Start_Request__executionArgument_PR {
	Start_Request__executionArgument_PR_NOTHING,	/* No components present */
	Start_Request__executionArgument_PR_simpleString
} Start_Request__executionArgument_PR;

/* Start-Request */
typedef struct Start_Request {
	Identifier_t	 programInvocationName;
	struct Start_Request__executionArgument {
		Start_Request__executionArgument_PR present;
		union Start_Request__executionArgument_u {
			MMSString_t	 simpleString;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *executionArgument;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Start_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Start_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _Start_Request_H_ */
