/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_TakeControl_Request_H_
#define	_TakeControl_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectName.h"
#include "Identifier.h"
#include "Priority.h"
#include "Unsigned32.h"
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ApplicationReference;

/* TakeControl-Request */
typedef struct TakeControl_Request {
	ObjectName_t	 semaphoreName;
	Identifier_t	*namedToken	/* OPTIONAL */;
	Priority_t	*priority	/* DEFAULT 64 */;
	Unsigned32_t	*acceptableDelay	/* OPTIONAL */;
	Unsigned32_t	*controlTimeOut	/* OPTIONAL */;
	BOOLEAN_t	*abortOnTimeOut	/* OPTIONAL */;
	BOOLEAN_t	*relinquishIfConnectionLost	/* DEFAULT TRUE */;
	struct ApplicationReference	*applicationToPreempt	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TakeControl_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TakeControl_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ApplicationReference.h"

#endif	/* _TakeControl_Request_H_ */
