/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-Object-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_ULState_H_
#define	_ULState_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ULState {
	ULState_non_existent	= 0,
	ULState_uploading	= 1,
	ULState_uploaded	= 2,
	ULState_u1	= 3,
	ULState_u2	= 4,
	ULState_u3	= 5,
	ULState_u4	= 6
} e_ULState;

/* ULState */
typedef long	 ULState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ULState;
asn_struct_free_f ULState_free;
asn_struct_print_f ULState_print;
asn_constr_check_f ULState_constraint;
ber_type_decoder_f ULState_decode_ber;
der_type_encoder_f ULState_encode_der;
xer_type_decoder_f ULState_decode_xer;
xer_type_encoder_f ULState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ULState_H_ */
