/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Unconfirmed_PDU_H_
#define	_Unconfirmed_PDU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UnconfirmedService.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Unconfirmed_Detail;

/* Unconfirmed-PDU */
typedef struct Unconfirmed_PDU {
	UnconfirmedService_t	 service;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct Unconfirmed_Detail	*service_ext	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Unconfirmed_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Unconfirmed_PDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Unconfirmed-Detail.h"

#endif	/* _Unconfirmed_PDU_H_ */
