/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "UnitControlUpload-Response.h"

static asn_TYPE_member_t asn_MBR_controlElements_2[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ControlElement,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_controlElements_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_controlElements_specs_2 = {
	sizeof(struct UnitControlUpload_Response__controlElements),
	offsetof(struct UnitControlUpload_Response__controlElements, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_controlElements_2 = {
	"controlElements",
	"controlElements",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_controlElements_tags_2,
	sizeof(asn_DEF_controlElements_tags_2)
		/sizeof(asn_DEF_controlElements_tags_2[0]) - 1, /* 1 */
	asn_DEF_controlElements_tags_2,	/* Same as above */
	sizeof(asn_DEF_controlElements_tags_2)
		/sizeof(asn_DEF_controlElements_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_controlElements_2,
	1,	/* Single element */
	&asn_SPC_controlElements_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_nextElement_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UnitControlUpload_Response__nextElement, choice.domain),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"domain"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UnitControlUpload_Response__nextElement, choice.ulsmID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ulsmID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UnitControlUpload_Response__nextElement, choice.programInvocation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"programInvocation"
		},
};
static asn_TYPE_tag2member_t asn_MAP_nextElement_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* domain at 1901 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* ulsmID at 1902 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* programInvocation at 1903 */
};
static asn_CHOICE_specifics_t asn_SPC_nextElement_specs_4 = {
	sizeof(struct UnitControlUpload_Response__nextElement),
	offsetof(struct UnitControlUpload_Response__nextElement, _asn_ctx),
	offsetof(struct UnitControlUpload_Response__nextElement, present),
	sizeof(((struct UnitControlUpload_Response__nextElement *)0)->present),
	asn_MAP_nextElement_tag2el_4,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nextElement_4 = {
	"nextElement",
	"nextElement",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_nextElement_4,
	3,	/* Elements count */
	&asn_SPC_nextElement_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_UnitControlUpload_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UnitControlUpload_Response, controlElements),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_controlElements_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"controlElements"
		},
	{ ATF_POINTER, 1, offsetof(struct UnitControlUpload_Response, nextElement),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_nextElement_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nextElement"
		},
};
static ber_tlv_tag_t asn_DEF_UnitControlUpload_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_UnitControlUpload_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* controlElements at 1899 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* domain at 1901 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* ulsmID at 1902 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 } /* programInvocation at 1903 */
};
static asn_SEQUENCE_specifics_t asn_SPC_UnitControlUpload_Response_specs_1 = {
	sizeof(struct UnitControlUpload_Response),
	offsetof(struct UnitControlUpload_Response, _asn_ctx),
	asn_MAP_UnitControlUpload_Response_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UnitControlUpload_Response = {
	"UnitControlUpload-Response",
	"UnitControlUpload-Response",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UnitControlUpload_Response_tags_1,
	sizeof(asn_DEF_UnitControlUpload_Response_tags_1)
		/sizeof(asn_DEF_UnitControlUpload_Response_tags_1[0]), /* 1 */
	asn_DEF_UnitControlUpload_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_UnitControlUpload_Response_tags_1)
		/sizeof(asn_DEF_UnitControlUpload_Response_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UnitControlUpload_Response_1,
	2,	/* Elements count */
	&asn_SPC_UnitControlUpload_Response_specs_1	/* Additional specs */
};

