/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "Unnamed-Variable-instance.h"

static asn_TYPE_member_t asn_MBR_Unnamed_Variable_instance_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Unnamed_Variable_instance, address),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Address,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"address"
		},
	{ ATF_POINTER, 0, offsetof(struct Unnamed_Variable_instance, accessControl),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Access_Control_List_instance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessControl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Unnamed_Variable_instance, typeDescription),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"typeDescription"
		},
};
static ber_tlv_tag_t asn_DEF_Unnamed_Variable_instance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Unnamed_Variable_instance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* address at 3018 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* accessControl at 3019 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* typeDescription at 3020 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Unnamed_Variable_instance_specs_1 = {
	sizeof(struct Unnamed_Variable_instance),
	offsetof(struct Unnamed_Variable_instance, _asn_ctx),
	asn_MAP_Unnamed_Variable_instance_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Unnamed_Variable_instance = {
	"Unnamed-Variable-instance",
	"Unnamed-Variable-instance",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Unnamed_Variable_instance_tags_1,
	sizeof(asn_DEF_Unnamed_Variable_instance_tags_1)
		/sizeof(asn_DEF_Unnamed_Variable_instance_tags_1[0]), /* 1 */
	asn_DEF_Unnamed_Variable_instance_tags_1,	/* Same as above */
	sizeof(asn_DEF_Unnamed_Variable_instance_tags_1)
		/sizeof(asn_DEF_Unnamed_Variable_instance_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Unnamed_Variable_instance_1,
	3,	/* Elements count */
	&asn_SPC_Unnamed_Variable_instance_specs_1	/* Additional specs */
};

