/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS-SCI-Module-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_Variable_List_Item_instance_H_
#define	_Variable_List_Item_instance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Unnamed_Variable_instance;
struct Named_Variable_instance;
struct AlternateAccess;

/* Variable-List-Item-instance */
typedef struct Variable_List_Item_instance {
	struct Unnamed_Variable_instance	*unnamedItem	/* OPTIONAL */;
	struct Named_Variable_instance	*namedItem	/* OPTIONAL */;
	struct AlternateAccess	*alternateAccess	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Variable_List_Item_instance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Variable_List_Item_instance;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Unnamed-Variable-instance.h"
#include "Named-Variable-instance.h"
#include "AlternateAccess.h"

#endif	/* _Variable_List_Item_instance_H_ */
