/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#include "asn_internal.h"

#include "VariableAccessSpecification.h"

static asn_TYPE_member_t asn_MBR_Member_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VariableAccessSpecification__listOfVariable__Member, variableSpecification),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_VariableSpecification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"variableSpecification"
		},
	{ ATF_POINTER, 1, offsetof(struct VariableAccessSpecification__listOfVariable__Member, alternateAccess),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlternateAccess,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternateAccess"
		},
};
static ber_tlv_tag_t asn_DEF_Member_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Member_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* name at 2052 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* address at 2053 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* variableDescription at 2055 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* scatteredAccessDescription at 2059 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 }, /* invalidated at 2060 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 } /* alternateAccess at 2048 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_3 = {
	sizeof(struct VariableAccessSpecification__listOfVariable__Member),
	offsetof(struct VariableAccessSpecification__listOfVariable__Member, _asn_ctx),
	asn_MAP_Member_tag2el_3,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_3 = {
	"SEQUENCE",
	"SEQUENCE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Member_tags_3,
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	asn_DEF_Member_tags_3,	/* Same as above */
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Member_3,
	2,	/* Elements count */
	&asn_SPC_Member_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_listOfVariable_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_listOfVariable_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfVariable_specs_2 = {
	sizeof(struct VariableAccessSpecification__listOfVariable),
	offsetof(struct VariableAccessSpecification__listOfVariable, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfVariable_2 = {
	"listOfVariable",
	"listOfVariable",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfVariable_tags_2,
	sizeof(asn_DEF_listOfVariable_tags_2)
		/sizeof(asn_DEF_listOfVariable_tags_2[0]) - 1, /* 1 */
	asn_DEF_listOfVariable_tags_2,	/* Same as above */
	sizeof(asn_DEF_listOfVariable_tags_2)
		/sizeof(asn_DEF_listOfVariable_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfVariable_2,
	1,	/* Single element */
	&asn_SPC_listOfVariable_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_VariableAccessSpecification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VariableAccessSpecification, choice.listOfVariable),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_listOfVariable_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfVariable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VariableAccessSpecification, choice.variableListName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"variableListName"
		},
};
static asn_TYPE_tag2member_t asn_MAP_VariableAccessSpecification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* listOfVariable at 2048 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* variableListName at 2049 */
};
static asn_CHOICE_specifics_t asn_SPC_VariableAccessSpecification_specs_1 = {
	sizeof(struct VariableAccessSpecification),
	offsetof(struct VariableAccessSpecification, _asn_ctx),
	offsetof(struct VariableAccessSpecification, present),
	sizeof(((struct VariableAccessSpecification *)0)->present),
	asn_MAP_VariableAccessSpecification_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_VariableAccessSpecification = {
	"VariableAccessSpecification",
	"VariableAccessSpecification",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_VariableAccessSpecification_1,
	2,	/* Elements count */
	&asn_SPC_VariableAccessSpecification_specs_1	/* Additional specs */
};

