/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_VMDReset_Request_H_
#define	_VMDReset_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VMDReset-Request */
typedef BOOLEAN_t	 VMDReset_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VMDReset_Request;
asn_struct_free_f VMDReset_Request_free;
asn_struct_print_f VMDReset_Request_print;
asn_constr_check_f VMDReset_Request_constraint;
ber_type_decoder_f VMDReset_Request_decode_ber;
der_type_encoder_f VMDReset_Request_encode_der;
xer_type_decoder_f VMDReset_Request_decode_xer;
xer_type_encoder_f VMDReset_Request_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VMDReset_Request_H_ */
