/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-9506-MMS-1"
 * 	found in "IEC61850.asn1"
 * 	`asn1c -S/skeletons -fnative-types`
 */

#ifndef	_WriteJournal_Request_H_
#define	_WriteJournal_Request_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectName.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EntryContent;

/* WriteJournal-Request */
typedef struct WriteJournal_Request {
	ObjectName_t	 journalName;
	struct WriteJournal_Request__listOfJournalEntry {
		A_SEQUENCE_OF(struct EntryContent) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfJournalEntry;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WriteJournal_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WriteJournal_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EntryContent.h"

#endif	/* _WriteJournal_Request_H_ */
